### ISSUE TITLE
Derive Copy and Clone for StatusEntry

### ISSUE THREAD

**Issue by Ciantic** [azasypkin/rust-cast#7]
I'm pretty new to Rust, but I think the `StatusEntry` and others could derive the Copy and Clone too so one could make helpers.

E.g. I've made [a helper defined like](https://github.com/Ciantic/casterson/blob/master/src/chromecast.rs#L29) this:

```rust
pub trait BaseMediaReceiver {
    fn play(&self);
    fn pause(&self);
    fn stop(&self);
    fn cast(&self, url: &str);
    fn get_current_time(&self) -> Option<f32>;
    // fn get_status(&self) -> Option<StatusEntry>;
}
```

But I can't implement the get_status because the StatusEntry is not copyable. Maybe I'm not yet understanding the Rust perfectly. However I keep getting type `&StatusEntry` from a `status.entries.first().unwrap()` call and I can't convert it back to `StatusEntry` because it's not copyable.

Thanks, great library! I've used JavaScript libraries for chromecast before, but boy I don't like those.

**Comment by Ciantic** [comment]
Okay, I figured I can just do:

```
 let mut status_list = cast_device
                .media
                .get_status(app.transport_id.as_str(), None)
                .unwrap()
                .entries
let status = status_list.remove(0);
```

However now I have problem that Serialize and Deserialize is not implemented, but that is a different issue altogether.

**Comment by azasypkin** [comment]
@Ciantic glad that you found the crate useful!

> I'm pretty new to Rust, but I think the StatusEntry and others could derive the Copy and Clone too so one could make helpers.

Unfortunately it wouldn't be easy/correct to add `Copy` everywhere since many of the structures use `String` fields (well, yeah, my first Rust project :see_no_evil:) and `String` obviously doesn't implement `Copy` automatically. Having said that I've just added `Clone` wherever it makes sense and `Copy` where it's possible and published [new version](https://crates.io/crates/rust_cast/0.15.0) (additionally switched crate to `2018` edition and upgraded dependencies).

I don't have a TV/HDMI display/enough time these days to work on this crate actively and happy to accept any improvements or fixes you may come up with!
